/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gymalphasoftware;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Admin
 */
public class manejoMembresiaPorCliente extends javax.swing.JFrame {

    String codigoMembresiaCliente;
    String fechaMembresia; /**
     * Creates new form manejoMembresiaPorCliente
     */
    public manejoMembresiaPorCliente() {
        initComponents();
        setLocationRelativeTo(null);//Código para centrar ventana
        CMembresiaPorCliente objetoMembresiaCliente = new CMembresiaPorCliente();
        objetoMembresiaCliente.mostrarMembresiaCliente(manejoMembresiasPorCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manejoMembresiasPorCliente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Manejo de Membresias por Cliente:");

        manejoMembresiasPorCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        manejoMembresiasPorCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        manejoMembresiasPorCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manejoMembresiasPorClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(manejoMembresiasPorCliente);

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setText("Crear registro +");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manejoMembresiasPorClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manejoMembresiasPorClienteMouseClicked

        int column = manejoMembresiasPorCliente.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/manejoMembresiasPorCliente.getRowHeight();

        if(row < manejoMembresiasPorCliente.getRowCount() && row >= 0 && column < manejoMembresiasPorCliente.getColumnCount() && column >= 0){
            Object value = manejoMembresiasPorCliente.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;

                if(boton.getName().equals("m")){
                    System.out.println("Hola m");
                    int fila = manejoMembresiasPorCliente.getSelectedRow();
                    codigoMembresiaCliente = manejoMembresiasPorCliente.getValueAt(fila,0).toString();
                    fechaMembresia = manejoMembresiasPorCliente.getValueAt(fila,2).toString();
                    try {
                        new modificarMembresiaCliente(codigoMembresiaCliente,fechaMembresia).setVisible(true);
                    } catch (SQLException ex) {
                        Logger.getLogger(manejoMembresiaPorCliente.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    this.dispose();
                }
                if(boton.getName().equals("e")){
                    System.out.println("Hola e");
                    int selectedRow = manejoMembresiasPorCliente.getSelectedRow();
                    System.out.println(selectedRow);
                    Object cellValue = manejoMembresiasPorCliente.getValueAt(selectedRow, 0);
                    String cellValueText = cellValue.toString();
                    System.out.println(cellValueText);
                    Object cellValue2 = manejoMembresiasPorCliente.getValueAt(selectedRow, 2);
                    String cellValueText2 = cellValue2.toString();
                    String[] parts = cellValueText2.split("-");
                    String day = parts[2];
                    String month = parts[1];
                    String year = parts[0];
                    String outputDate = day + "/" + month + "/" + year;
                    CMembresiaPorCliente objetoMembresiaPorCliente = new CMembresiaPorCliente();
                    objetoMembresiaPorCliente.EliminarMembresiaCliente(cellValueText,outputDate);
                    this.dispose();
                    new manejoMembresiaPorCliente().setVisible(true);
                }

            }
        }
    }//GEN-LAST:event_manejoMembresiasPorClienteMouseClicked
    public String devolverCodigo() {
        return codigoMembresiaCliente;
    }
    public String devolverFecha() {
        return fechaMembresia;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new nuevaMembresiaPorCliente().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            com.formdev.flatlaf.themes.FlatMacLightLaf.setup();
         } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manejoMembresiaPorCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manejoMembresiasPorCliente;
    // End of variables declaration//GEN-END:variables
}
