/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gymalphasoftware;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatMonokaiProIJTheme;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class manejoMembresias extends javax.swing.JFrame {

    Integer condigoMembresias;
    public manejoMembresias() {
        initComponents();
        initStyles();
        setLocationRelativeTo(null);//Código para centrar ventana
        CMembresias objetoMembresias = new CMembresias();
        objetoMembresias.mostrarMembresias(tblManejoMembresias);
    }

    private void initStyles(){
        tblManejoMembresias.putClientProperty("FlatLaf.styleClass", "h3");
        tblManejoMembresias.getTableHeader().putClientProperty("FlatLaf.styleClass", "h3");
        btnCrearMembresia.putClientProperty("FlatLaf.styleClass", "h3");
        btnVolver.putClientProperty("FlatLaf.styleClass", "h3");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblManejoMembresias = new javax.swing.JTable();
        btnCrearMembresia = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Manejo de membresías:");

        tblManejoMembresias.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblManejoMembresias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblManejoMembresias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblManejoMembresiasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblManejoMembresias);

        btnCrearMembresia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCrearMembresia.setText("Crear membresia");
        btnCrearMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMembresiaActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearMembresia)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearMembresia)
                    .addComponent(btnVolver))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblManejoMembresiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblManejoMembresiasMouseClicked

        int column = tblManejoMembresias.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblManejoMembresias.getRowHeight();

        if(row < tblManejoMembresias.getRowCount() && row >= 0 && column < tblManejoMembresias.getColumnCount() && column >= 0){
            Object value = tblManejoMembresias.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                boton.putClientProperty("FlatLaf.styleClass", "h3");
                if(boton.getName().equals("m")){
                    System.out.println("Hola m");
                    int fila = tblManejoMembresias.getSelectedRow();
                    condigoMembresias = Integer.parseInt(tblManejoMembresias.getValueAt(fila,0).toString());

                }
                if(boton.getName().equals("e")){
                    System.out.println("Hola e");
                    int selectedRow = tblManejoMembresias.getSelectedRow();
                    System.out.println(selectedRow);
                    Object cellValue = tblManejoMembresias.getValueAt(selectedRow, 0);
                    Integer cellValueText = Integer.parseInt(cellValue.toString());
                    System.out.println(cellValueText);
                    CMembresias objetoMembresias = new CMembresias();
                    objetoMembresias.EliminarMembresia(cellValueText);
                    new manejoMembresias().setVisible(true);
                }

            }
        }
    }//GEN-LAST:event_tblManejoMembresiasMouseClicked
    public Integer devolverCodigo() {
        return condigoMembresias;
    }
    private void btnCrearMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMembresiaActionPerformed
        this.dispose();
        //new nuevaMembresia().setVisible(true);
    }//GEN-LAST:event_btnCrearMembresiaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            com.formdev.flatlaf.themes.FlatMacLightLaf.setup();
         } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manejoMembresias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearMembresia;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblManejoMembresias;
    // End of variables declaration//GEN-END:variables
}
